### ISSUE TITLE
lux not in data table - Incomplete untested code

### ISSUE THREAD

**Issue by ThingEngineer** [electricimp/Plotly#6]
In the device code lux is never added to the data table while day is added to the data table but not used in the agent code.

In the agent code lux is assumed to be in the reading array but it is not because it was never in the data table when for the agent.send call in the device.

I really love electric imp and all the example code. However I feel that there are to many code examples that have obviously not been tested.

**Comment by aboyett** [comment]
This should be resolved with the recent merging of #5
